# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-macie
  description: Use AI/ML and pattern matching to identify and protect sensitive data in AWS
  homepage: https://cloudposse.com/accelerate
  topics: macie, aws, security, machine-lerning, privacy, compliance, terraform, terraform-modules


