# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-macie
  description: Terraform module to provision Amazon Macie - a fully managed data security and data privacy service that uses machine learning and pattern matching to discover and protect your sensitive data in AWS
  homepage: https://cloudposse.com/accelerate
  topics: macie, aws, security, machine-lerning, privacy, compliance, terraform, terraform-modules
